'use strict';
// A 层：所有学校的轻量基础数据（美国看看 / 全球看看 / 地图都读这里）。字段说明见 SPEC.md 第 3.3 节。
// researchStatus: new 新发现 | priority 优先研究 | secondary 第二优先 | watch 观察 | climate 已研究·因气候暂不考虑 | none 仅排名层
// climate.band: 1 极冷 … 5 温和（最冷月日均温约数，待官方核实）；outOfScope=true 表示不在 Mira 的选校范围
const schools = [
  {
    "id": "richmond",
    "name": "University of Richmond",
    "cnName": "里士满大学",
    "country": "US",
    "city": "Richmond",
    "state": "Virginia",
    "region": "South",
    "lat": 37.5751,
    "lng": -77.5407,
    "kind": "lac",
    "institutionType": "Private Liberal Arts University",
    "size": "medium",
    "undergradEnrollment": "约 3,100 人",
    "undergradEnrollmentYear": "2025 秋季",
    "campusSetting": "Suburban",
    "rankings": {
      "usnewsNU": null,
      "usnewsLAC": 21,
      "qs": null
    },
    "climate": {
      "coldMonthMeanC": 3.5,
      "band": 4,
      "outOfScope": false,
      "note": "",
      "verified": false
    },
    "howToStudy": "",
    "stemTag": false,
    "costOfAttendanceUSD": null,
    "officialUrl": "https://www.richmond.edu/",
    "admissionsUrl": "https://admission.richmond.edu/",
    "heroImage": null,
    "heroImageCredit": null,
    "researchStatus": "priority"
  },
  {
    "id": "macalester",
    "name": "Macalester College",
    "cnName": "麦卡莱斯特学院",
    "country": "US",
    "city": "Saint Paul",
    "state": "Minnesota",
    "region": "Midwest",
    "lat": 44.9394,
    "lng": -93.1698,
    "kind": "lac",
    "institutionType": "Private Liberal Arts College",
    "size": "small",
    "undergradEnrollment": "约 2,000 人",
    "undergradEnrollmentYear": "2026 春季",
    "campusSetting": "Urban",
    "rankings": {
      "usnewsNU": null,
      "usnewsLAC": 28,
      "qs": null
    },
    "climate": {
      "coldMonthMeanC": -9.5,
      "band": 1,
      "outOfScope": true,
      "note": "",
      "verified": false
    },
    "howToStudy": "",
    "stemTag": false,
    "costOfAttendanceUSD": null,
    "officialUrl": "https://www.macalester.edu/",
    "admissionsUrl": "https://www.macalester.edu/admissions/",
    "heroImage": null,
    "heroImageCredit": null,
    "researchStatus": "climate"
  },
  {
    "id": "denison",
    "name": "Denison University",
    "cnName": "丹尼森大学",
    "country": "US",
    "city": "Granville",
    "state": "Ohio",
    "region": "Midwest",
    "lat": 40.0725,
    "lng": -82.5227,
    "kind": "lac",
    "institutionType": "Private Liberal Arts College",
    "size": "small",
    "undergradEnrollment": "约 2,500 人",
    "undergradEnrollmentYear": "2025 秋季",
    "campusSetting": "Small town",
    "rankings": {
      "usnewsNU": null,
      "usnewsLAC": null,
      "qs": null
    },
    "climate": {
      "coldMonthMeanC": -2,
      "band": 3,
      "outOfScope": false,
      "note": "",
      "verified": false
    },
    "howToStudy": "",
    "stemTag": false,
    "costOfAttendanceUSD": null,
    "officialUrl": "https://denison.edu/",
    "admissionsUrl": "https://denison.edu/campus/admission",
    "heroImage": null,
    "heroImageCredit": null,
    "researchStatus": "priority"
  },
  {
    "id": "dickinson",
    "name": "Dickinson College",
    "cnName": "狄金森学院",
    "country": "US",
    "city": "Carlisle",
    "state": "Pennsylvania",
    "region": "Northeast",
    "lat": 40.2023,
    "lng": -77.1975,
    "kind": "lac",
    "institutionType": "Private Liberal Arts College",
    "size": "small",
    "undergradEnrollment": "约 2,000 人",
    "undergradEnrollmentYear": "2026 秋季",
    "campusSetting": "College town",
    "rankings": {
      "usnewsNU": null,
      "usnewsLAC": null,
      "qs": null
    },
    "climate": {
      "coldMonthMeanC": -1,
      "band": 3,
      "outOfScope": false,
      "note": "",
      "verified": false
    },
    "howToStudy": "",
    "stemTag": false,
    "costOfAttendanceUSD": null,
    "officialUrl": "https://www.dickinson.edu/",
    "admissionsUrl": "https://www.dickinson.edu/homepage/287/admissions",
    "heroImage": null,
    "heroImageCredit": null,
    "researchStatus": "priority"
  },
  {
    "id": "wooster",
    "name": "College of Wooster",
    "cnName": "伍斯特学院",
    "country": "US",
    "city": "Wooster",
    "state": "Ohio",
    "region": "Midwest",
    "lat": 40.8117,
    "lng": -81.9351,
    "kind": "lac",
    "institutionType": "Private Liberal Arts College",
    "size": "small",
    "undergradEnrollment": "1,600+ 人",
    "undergradEnrollmentYear": "",
    "campusSetting": "College town",
    "rankings": {
      "usnewsNU": null,
      "usnewsLAC": null,
      "qs": null
    },
    "climate": {
      "coldMonthMeanC": -3,
      "band": 3,
      "outOfScope": false,
      "note": "",
      "verified": false
    },
    "howToStudy": "",
    "stemTag": false,
    "costOfAttendanceUSD": null,
    "officialUrl": "https://wooster.edu/",
    "admissionsUrl": "https://wooster.edu/admissions",
    "heroImage": null,
    "heroImageCredit": null,
    "researchStatus": "watch"
  },
  {
    "id": "st-olaf",
    "name": "St. Olaf College",
    "cnName": "圣奥拉夫学院",
    "country": "US",
    "city": "Northfield",
    "state": "Minnesota",
    "region": "Midwest",
    "lat": 44.4583,
    "lng": -93.1849,
    "kind": "lac",
    "institutionType": "Private Liberal Arts College",
    "size": "medium",
    "undergradEnrollment": "约 3,100 人",
    "undergradEnrollmentYear": "2025–26",
    "campusSetting": "Small town",
    "rankings": {
      "usnewsNU": null,
      "usnewsLAC": null,
      "qs": null
    },
    "climate": {
      "coldMonthMeanC": -10,
      "band": 1,
      "outOfScope": true,
      "note": "",
      "verified": false
    },
    "howToStudy": "",
    "stemTag": false,
    "costOfAttendanceUSD": null,
    "officialUrl": "https://www.stolaf.edu/",
    "admissionsUrl": "https://wp.stolaf.edu/admissions/",
    "heroImage": null,
    "heroImageCredit": null,
    "researchStatus": "climate"
  },
  {
    "id": "oberlin",
    "name": "Oberlin College",
    "cnName": "欧柏林学院",
    "country": "US",
    "city": "Oberlin",
    "state": "Ohio",
    "region": "Midwest",
    "lat": 41.2939,
    "lng": -82.2174,
    "kind": "lac",
    "institutionType": "Private Liberal Arts College and Conservatory",
    "size": "medium",
    "undergradEnrollment": "约 3,100 人",
    "undergradEnrollmentYear": "2025–26",
    "campusSetting": "College town",
    "rankings": {
      "usnewsNU": null,
      "usnewsLAC": null,
      "qs": null
    },
    "climate": {
      "coldMonthMeanC": -2.5,
      "band": 3,
      "outOfScope": false,
      "note": "",
      "verified": false
    },
    "howToStudy": "",
    "stemTag": false,
    "costOfAttendanceUSD": null,
    "officialUrl": "https://www.oberlin.edu/",
    "admissionsUrl": "https://www.oberlin.edu/admissions-and-aid",
    "heroImage": null,
    "heroImageCredit": null,
    "researchStatus": "secondary"
  },
  {
    "id": "rochester",
    "name": "University of Rochester",
    "cnName": "罗切斯特大学",
    "country": "US",
    "city": "Rochester",
    "state": "New York",
    "region": "Northeast",
    "lat": 43.1292,
    "lng": -77.628,
    "kind": "university",
    "institutionType": "Private Research University",
    "size": "medium",
    "undergradEnrollment": "约 6,100 人",
    "undergradEnrollmentYear": "2025 秋季",
    "campusSetting": "Urban",
    "rankings": {
      "usnewsNU": 49,
      "usnewsLAC": null,
      "qs": null
    },
    "climate": {
      "coldMonthMeanC": -4,
      "band": 2,
      "outOfScope": false,
      "note": "湖效应降雪多",
      "verified": false
    },
    "howToStudy": "",
    "stemTag": false,
    "costOfAttendanceUSD": null,
    "officialUrl": "https://www.rochester.edu/",
    "admissionsUrl": "https://admissions.rochester.edu/",
    "heroImage": null,
    "heroImageCredit": null,
    "researchStatus": "priority"
  },
  {
    "id": "brandeis",
    "name": "Brandeis University",
    "cnName": "布兰迪斯大学",
    "country": "US",
    "city": "Waltham",
    "state": "Massachusetts",
    "region": "Northeast",
    "lat": 42.3657,
    "lng": -71.2584,
    "kind": "university",
    "institutionType": "Private Research University",
    "size": "medium",
    "undergradEnrollment": "约 3,300 人",
    "undergradEnrollmentYear": "2025 秋季",
    "campusSetting": "Suburban",
    "rankings": {
      "usnewsNU": null,
      "usnewsLAC": null,
      "qs": null
    },
    "climate": {
      "coldMonthMeanC": -1.5,
      "band": 3,
      "outOfScope": false,
      "note": "",
      "verified": false
    },
    "howToStudy": "",
    "stemTag": false,
    "costOfAttendanceUSD": null,
    "officialUrl": "https://www.brandeis.edu/",
    "admissionsUrl": "https://www.brandeis.edu/admissions/",
    "heroImage": null,
    "heroImageCredit": null,
    "researchStatus": "watch"
  },
  {
    "id": "william-mary",
    "name": "William & Mary",
    "cnName": "威廉玛丽大学",
    "country": "US",
    "city": "Williamsburg",
    "state": "Virginia",
    "region": "South",
    "lat": 37.271,
    "lng": -76.7138,
    "kind": "university",
    "institutionType": "Public Research University",
    "size": "medium",
    "undergradEnrollment": "约 7,000 人",
    "undergradEnrollmentYear": "2025 秋季",
    "campusSetting": "College town",
    "rankings": {
      "usnewsNU": 52,
      "usnewsLAC": null,
      "qs": null
    },
    "climate": {
      "coldMonthMeanC": 4.5,
      "band": 4,
      "outOfScope": false,
      "note": "",
      "verified": false
    },
    "howToStudy": "",
    "stemTag": false,
    "costOfAttendanceUSD": null,
    "officialUrl": "https://www.wm.edu/",
    "admissionsUrl": "https://www.wm.edu/admission/undergraduateadmission/",
    "heroImage": null,
    "heroImageCredit": null,
    "researchStatus": "priority"
  },
  {
    "id": "wake-forest",
    "name": "Wake Forest University",
    "cnName": "维克森林大学",
    "country": "US",
    "city": "Winston-Salem",
    "state": "North Carolina",
    "region": "South",
    "lat": 36.1341,
    "lng": -80.2783,
    "kind": "university",
    "institutionType": "Private Research University",
    "size": "medium",
    "undergradEnrollment": "约 5,600 人",
    "undergradEnrollmentYear": "2025 秋季",
    "campusSetting": "",
    "rankings": {
      "usnewsNU": 34,
      "usnewsLAC": null,
      "qs": null
    },
    "climate": {
      "coldMonthMeanC": 3.5,
      "band": 4,
      "outOfScope": false,
      "note": "",
      "verified": false
    },
    "howToStudy": "",
    "stemTag": false,
    "costOfAttendanceUSD": null,
    "officialUrl": "https://www.wfu.edu/",
    "admissionsUrl": "https://admissions.wfu.edu/",
    "heroImage": null,
    "heroImageCredit": null,
    "researchStatus": "priority"
  },
  {
    "id": "clark",
    "name": "Clark University",
    "cnName": "克拉克大学",
    "country": "US",
    "city": "Worcester",
    "state": "Massachusetts",
    "region": "Northeast",
    "lat": 42.2515,
    "lng": -71.8233,
    "kind": "university",
    "institutionType": "Private Research University",
    "size": "small",
    "undergradEnrollment": "约 2,100 人",
    "undergradEnrollmentYear": "",
    "campusSetting": "Urban",
    "rankings": {
      "usnewsNU": null,
      "usnewsLAC": null,
      "qs": null
    },
    "climate": {
      "coldMonthMeanC": -4,
      "band": 2,
      "outOfScope": false,
      "note": "",
      "verified": false
    },
    "howToStudy": "",
    "stemTag": false,
    "costOfAttendanceUSD": null,
    "officialUrl": "https://www.clarku.edu/",
    "admissionsUrl": "https://www.clarku.edu/undergraduate-admissions/",
    "heroImage": null,
    "heroImageCredit": null,
    "researchStatus": "watch"
  },
  {
    "id": "lehigh",
    "name": "Lehigh University",
    "cnName": "理海大学",
    "country": "US",
    "city": "Bethlehem",
    "state": "Pennsylvania",
    "region": "Northeast",
    "lat": 40.6079,
    "lng": -75.3783,
    "kind": "university",
    "institutionType": "Private Research University",
    "size": "medium",
    "undergradEnrollment": "约 6,000 人",
    "undergradEnrollmentYear": "2025 秋季",
    "campusSetting": "",
    "rankings": {
      "usnewsNU": 44,
      "usnewsLAC": null,
      "qs": null
    },
    "climate": {
      "coldMonthMeanC": -1.5,
      "band": 3,
      "outOfScope": false,
      "note": "",
      "verified": false
    },
    "howToStudy": "",
    "stemTag": false,
    "costOfAttendanceUSD": null,
    "officialUrl": "https://www.lehigh.edu/",
    "admissionsUrl": "https://www2.lehigh.edu/admissions",
    "heroImage": null,
    "heroImageCredit": null,
    "researchStatus": "priority"
  },
  {
    "id": "syracuse",
    "name": "Syracuse University",
    "cnName": "雪城大学",
    "country": "US",
    "city": "Syracuse",
    "state": "New York",
    "region": "Northeast",
    "lat": 43.0392,
    "lng": -76.1351,
    "kind": "university",
    "institutionType": "Private Research University",
    "size": "large",
    "undergradEnrollment": "15,000+ 人",
    "undergradEnrollmentYear": "",
    "campusSetting": "",
    "rankings": {
      "usnewsNU": null,
      "usnewsLAC": null,
      "qs": null
    },
    "climate": {
      "coldMonthMeanC": -4.5,
      "band": 2,
      "outOfScope": false,
      "note": "全美降雪最多的城市之一",
      "verified": false
    },
    "howToStudy": "",
    "stemTag": false,
    "costOfAttendanceUSD": null,
    "officialUrl": "https://www.syracuse.edu/",
    "admissionsUrl": "https://www.syracuse.edu/admissions-aid/application-process/undergraduate/",
    "heroImage": null,
    "heroImageCredit": null,
    "researchStatus": "priority"
  },
  {
    "id": "denver",
    "name": "University of Denver",
    "cnName": "丹佛大学",
    "country": "US",
    "city": "Denver",
    "state": "Colorado",
    "region": "West",
    "lat": 39.6781,
    "lng": -104.9618,
    "kind": "university",
    "institutionType": "Private Research University",
    "size": "medium",
    "undergradEnrollment": "约 5,800 人",
    "undergradEnrollmentYear": "2025–26",
    "campusSetting": "Urban",
    "rankings": {
      "usnewsNU": null,
      "usnewsLAC": null,
      "qs": null
    },
    "climate": {
      "coldMonthMeanC": -0.5,
      "band": 3,
      "outOfScope": false,
      "note": "平均气温不算低，但常下雪",
      "verified": false
    },
    "howToStudy": "",
    "stemTag": false,
    "costOfAttendanceUSD": null,
    "officialUrl": "https://www.du.edu/",
    "admissionsUrl": "https://www.du.edu/admission-aid/undergraduate",
    "heroImage": null,
    "heroImageCredit": null,
    "researchStatus": "watch"
  },
  {
    "id": "pitt",
    "name": "University of Pittsburgh",
    "cnName": "匹兹堡大学",
    "country": "US",
    "city": "Pittsburgh",
    "state": "Pennsylvania",
    "region": "Northeast",
    "lat": 40.4443,
    "lng": -79.9608,
    "kind": "university",
    "institutionType": "Public Research University",
    "size": "large",
    "undergradEnrollment": "约 21,400 人",
    "undergradEnrollmentYear": "2025 秋季",
    "campusSetting": "Urban",
    "rankings": {
      "usnewsNU": null,
      "usnewsLAC": null,
      "qs": null
    },
    "climate": {
      "coldMonthMeanC": -2,
      "band": 3,
      "outOfScope": false,
      "note": "",
      "verified": false
    },
    "howToStudy": "",
    "stemTag": false,
    "costOfAttendanceUSD": null,
    "officialUrl": "https://www.pitt.edu/",
    "admissionsUrl": "https://admissions.pitt.edu/",
    "heroImage": null,
    "heroImageCredit": null,
    "researchStatus": "secondary"
  },
  {
    "id": "umass-amherst",
    "name": "University of Massachusetts Amherst",
    "cnName": "马萨诸塞大学阿默斯特分校",
    "country": "US",
    "city": "Amherst",
    "state": "Massachusetts",
    "region": "Northeast",
    "lat": 42.3868,
    "lng": -72.5301,
    "kind": "university",
    "institutionType": "Public Research University",
    "size": "large",
    "undergradEnrollment": "约 24,000 人",
    "undergradEnrollmentYear": "2025 秋季",
    "campusSetting": "College town",
    "rankings": {
      "usnewsNU": null,
      "usnewsLAC": null,
      "qs": null
    },
    "climate": {
      "coldMonthMeanC": -4.5,
      "band": 2,
      "outOfScope": false,
      "note": "",
      "verified": false
    },
    "howToStudy": "",
    "stemTag": false,
    "costOfAttendanceUSD": null,
    "officialUrl": "https://www.umass.edu/",
    "admissionsUrl": "https://www.umass.edu/admissions/undergraduate-admissions",
    "heroImage": null,
    "heroImageCredit": null,
    "researchStatus": "secondary"
  },
  {
    "id": "uw-madison",
    "name": "University of Wisconsin–Madison",
    "cnName": "威斯康星大学麦迪逊分校",
    "country": "US",
    "city": "Madison",
    "state": "Wisconsin",
    "region": "Midwest",
    "lat": 43.0766,
    "lng": -89.4125,
    "kind": "university",
    "institutionType": "Public Research University",
    "size": "large",
    "undergradEnrollment": "约 37,200 人",
    "undergradEnrollmentYear": "2025 秋季",
    "campusSetting": "Urban",
    "rankings": {
      "usnewsNU": 34,
      "usnewsLAC": null,
      "qs": null
    },
    "climate": {
      "coldMonthMeanC": -7,
      "band": 1,
      "outOfScope": true,
      "note": "",
      "verified": false
    },
    "howToStudy": "",
    "stemTag": false,
    "costOfAttendanceUSD": null,
    "officialUrl": "https://www.wisc.edu/",
    "admissionsUrl": "https://admissions.wisc.edu/",
    "heroImage": null,
    "heroImageCredit": null,
    "researchStatus": "climate"
  },
  {
    "id": "american",
    "name": "American University",
    "cnName": "美利坚大学",
    "country": "US",
    "city": "Washington",
    "state": "District of Columbia",
    "region": "South",
    "lat": 38.9379,
    "lng": -77.0901,
    "kind": "university",
    "institutionType": "Private Research University",
    "size": "medium",
    "undergradEnrollment": "约 7,500 人",
    "undergradEnrollmentYear": "2024 秋季",
    "campusSetting": "Urban",
    "rankings": {
      "usnewsNU": null,
      "usnewsLAC": null,
      "qs": null
    },
    "climate": {
      "coldMonthMeanC": 2.5,
      "band": 4,
      "outOfScope": false,
      "note": "",
      "verified": false
    },
    "howToStudy": "",
    "stemTag": false,
    "costOfAttendanceUSD": null,
    "officialUrl": "https://www.american.edu/",
    "admissionsUrl": "https://www.american.edu/admissions/",
    "heroImage": null,
    "heroImageCredit": null,
    "researchStatus": "watch"
  },
  {
    "id": "gwu",
    "name": "George Washington University",
    "cnName": "乔治华盛顿大学",
    "country": "US",
    "city": "Washington",
    "state": "District of Columbia",
    "region": "South",
    "lat": 38.8997,
    "lng": -77.0486,
    "kind": "university",
    "institutionType": "Private Research University",
    "size": "large",
    "undergradEnrollment": "约 11,500 人",
    "undergradEnrollmentYear": "2025–26",
    "campusSetting": "Urban",
    "rankings": {
      "usnewsNU": null,
      "usnewsLAC": null,
      "qs": null
    },
    "climate": {
      "coldMonthMeanC": 2.5,
      "band": 4,
      "outOfScope": false,
      "note": "",
      "verified": false
    },
    "howToStudy": "",
    "stemTag": false,
    "costOfAttendanceUSD": null,
    "officialUrl": "https://www.gwu.edu/",
    "admissionsUrl": "https://undergraduate.admissions.gwu.edu/",
    "heroImage": null,
    "heroImageCredit": null,
    "researchStatus": "watch"
  }
];
